### ISSUE TITLE
Debugging should be easier.

### ISSUE THREAD

**Issue by nidhir-systango** [kevinsawicki/signcode#6]
please  provide some helpful error message on failiure,

in my electron app i am running 
signcode  ./dist/win/CoDesktopElectron.msi --cert ./assets/certificate/Certificates.p12 --prompt --name 'Co Desktop' --url 'https://app.onepgr.com'" from cli and getting error

> CoDesktopElectron@1.0.0 sign-installer C:\Users\admin\Downloads\New folder\new2\win_codesktop
> signcode ./dist/win/CoDesktopElectron.msi --cert ./assets/certificate/Certificates.p12 --prompt --name 'Co Desktop' --url 'https://app.onepgr.com'

prompt: Enter Password:
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\admin\Downloads\New folder\new2\win_codesktop\node_modules\signcode\vendor\win32\osslsigncode ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "sign-installer"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! CoDesktopElectron@1.0.0 sign-installer: `signcode ./dist/win/CoDesktopElectron.msi --cert ./assets/certificate/Certificates.p12 --prompt --name 'Co Desktop' --url 'https://app.onepgr.com'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the CoDesktopElectron@1.0.0 sign-installer script 'signcode ./dist/win/CoDesktopElectron.msi --cert ./assets/certificate/Certificates.p12 --prompt --name 'Co Desktop' --url 'https://app.onepgr.com''.
npm ERR! This is most likely a problem with the CoDesktopElectron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     signcode ./dist/win/CoDesktopElectron.msi --cert ./assets/certificate/Certificates.p12 --prompt --name 'Co Desktop' --url 'https://app.onepgr.com'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs CoDesktopElectron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls CoDesktopElectron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\admin\Downloads\New folder\new2\win_codesktop\npm-debug.log

searched all over it,can't find any support

**Comment by jonathan-roy** [comment]
Did you find the cause of this error?

**Comment by SatishReddy006** [comment]
Have you find solution for signing msi/exe application
